name: build

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    runs-on: ubuntu-18.04

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        node-version: [11, 12]
        python-version: [3.7, 3.8]

    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install jupyterlab
        run: python -m pip install jupyterlab

      - uses: actions/checkout@v1

      - name: Install JS dependencies and build
        run: jlpm
