name: build

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install jupyterlab
        run: python -m pip install jupyterlab

      - uses: actions/checkout@v2

      - name: Install JS dependencies and build
        run: jlpm

      - name: Bump version
        uses: "phips28/gh-action-bump-version@v5.0.18"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
